packages:
  - 'packages/*'
  - 'packages/adapters/*'
  - 'apps/*'
  - 'examples/*'

catalog:
  vite: ^7.1.4
  '@vitejs/plugin-react': ^5.0.0
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
  jsdom: ^24.1.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.0.1
  '@testing-library/user-event': ^14.5.2
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  typescript: ^5.8.3
