name: Bug Report
description: File a bug report to help us improve Better Tables
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package is affected by this bug?
      options:
        - "@better-tables/core"
        - "@better-tables/ui"
        - "@better-tables/adapters-drizzle"
        - "Multiple packages"
        - "Not sure"
      default: 0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your environment details (OS, Node version, Bun version, browser, etc.)
      placeholder: "OS: Windows 11, Node: 20.x, Bun: 1.3.1, Browser: Chrome 120"
    validations:
      required: false

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, add a minimal code example to help reproduce the bug.
      placeholder: |
        ```typescript
        // Your code here
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, error messages, or related issues about the problem here.
      placeholder: Any other information that might be helpful...
    validations:
      required: false

