import type { SupportAssignee, SupportCustomer, SupportTicket } from './schema';

export const supportSeed = {
  customers: [
    { id: 1, name: 'Northwind Labs', company: 'Northwind Labs', plan: 'enterprise', region: 'na' },
    { id: 2, name: 'Brightline Health', company: 'Brightline Health', plan: 'pro', region: 'na' },
    { id: 3, name: 'Atlas Freight', company: 'Atlas Freight', plan: 'enterprise', region: 'emea' },
    { id: 4, name: 'Studio Kite', company: 'Studio Kite', plan: 'starter', region: 'apac' },
    { id: 5, name: 'Harbor Metrics', company: 'Harbor Metrics', plan: 'pro', region: 'emea' },
    { id: 6, name: 'Signal Ridge', company: 'Signal Ridge', plan: 'enterprise', region: 'na' },
  ] satisfies SupportCustomer[],

  assignees: [
    { id: 1, name: 'Maya Chen', team: 'tier2', shift: 'day' },
    { id: 2, name: 'Jordan Blake', team: 'tier1', shift: 'day' },
    { id: 3, name: 'Priya Nair', team: 'escalation', shift: 'night' },
    { id: 4, name: 'Alex Mercer', team: 'tier1', shift: 'night' },
    { id: 5, name: 'Sam Ortiz', team: 'tier2', shift: 'day' },
  ] satisfies SupportAssignee[],

  tickets: [
    {
      id: 101,
      subject: 'SSO login fails for enterprise admins',
      status: 'escalated',
      priority: 'urgent',
      channel: 'email',
      customerId: 1,
      assigneeId: 3,
      slaBreached: true,
      createdAt: new Date('2026-07-10T09:12:00Z'),
    },
    {
      id: 102,
      subject: 'Webhook retries stuck in pending state',
      status: 'open',
      priority: 'high',
      channel: 'chat',
      customerId: 6,
      assigneeId: 1,
      slaBreached: false,
      createdAt: new Date('2026-07-11T14:30:00Z'),
    },
    {
      id: 103,
      subject: 'Export queue timing out on large workspaces',
      status: 'pending',
      priority: 'high',
      channel: 'email',
      customerId: 3,
      assigneeId: 5,
      slaBreached: false,
      createdAt: new Date('2026-07-11T16:05:00Z'),
    },
    {
      id: 104,
      subject: 'Billing portal shows duplicate invoices',
      status: 'open',
      priority: 'medium',
      channel: 'email',
      customerId: 2,
      assigneeId: 2,
      slaBreached: false,
      createdAt: new Date('2026-07-12T08:40:00Z'),
    },
    {
      id: 105,
      subject: 'Chat widget missing on mobile Safari',
      status: 'resolved',
      priority: 'medium',
      channel: 'chat',
      customerId: 4,
      assigneeId: 2,
      slaBreached: false,
      createdAt: new Date('2026-07-08T11:20:00Z'),
    },
    {
      id: 106,
      subject: 'API rate limits not reflected in dashboard',
      status: 'open',
      priority: 'high',
      channel: 'phone',
      customerId: 6,
      assigneeId: 1,
      slaBreached: true,
      createdAt: new Date('2026-07-12T19:45:00Z'),
    },
    {
      id: 107,
      subject: 'Seat provisioning delay after upgrade',
      status: 'pending',
      priority: 'medium',
      channel: 'email',
      customerId: 5,
      assigneeId: 4,
      slaBreached: false,
      createdAt: new Date('2026-07-09T13:10:00Z'),
    },
    {
      id: 108,
      subject: 'Audit log export missing assignee events',
      status: 'escalated',
      priority: 'urgent',
      channel: 'email',
      customerId: 1,
      assigneeId: 3,
      slaBreached: true,
      createdAt: new Date('2026-07-12T22:18:00Z'),
    },
    {
      id: 109,
      subject: 'Starter plan cannot invite collaborators',
      status: 'resolved',
      priority: 'low',
      channel: 'chat',
      customerId: 4,
      assigneeId: 2,
      slaBreached: false,
      createdAt: new Date('2026-07-07T10:05:00Z'),
    },
    {
      id: 110,
      subject: 'Phone support callback never arrived',
      status: 'open',
      priority: 'high',
      channel: 'phone',
      customerId: 3,
      assigneeId: 5,
      slaBreached: false,
      createdAt: new Date('2026-07-13T07:55:00Z'),
    },
    {
      id: 111,
      subject: 'Region routing sends EMEA traffic to NA cluster',
      status: 'open',
      priority: 'urgent',
      channel: 'email',
      customerId: 3,
      assigneeId: 3,
      slaBreached: true,
      createdAt: new Date('2026-07-13T09:30:00Z'),
    },
    {
      id: 112,
      subject: 'Night shift handoff notes not visible',
      status: 'pending',
      priority: 'low',
      channel: 'chat',
      customerId: 5,
      assigneeId: 4,
      slaBreached: false,
      createdAt: new Date('2026-07-10T23:40:00Z'),
    },
    {
      id: 113,
      subject: 'Custom domain verification email expired',
      status: 'resolved',
      priority: 'medium',
      channel: 'email',
      customerId: 2,
      assigneeId: 1,
      slaBreached: false,
      createdAt: new Date('2026-07-06T15:22:00Z'),
    },
    {
      id: 114,
      subject: 'Bulk user import fails on unicode names',
      status: 'open',
      priority: 'medium',
      channel: 'email',
      customerId: 6,
      assigneeId: 5,
      slaBreached: false,
      createdAt: new Date('2026-07-12T12:08:00Z'),
    },
    {
      id: 115,
      subject: 'Escalation queue missing SLA breach badge',
      status: 'escalated',
      priority: 'high',
      channel: 'chat',
      customerId: 1,
      assigneeId: 3,
      slaBreached: true,
      createdAt: new Date('2026-07-13T11:05:00Z'),
    },
    {
      id: 116,
      subject: 'Pro plan analytics widget shows stale totals',
      status: 'pending',
      priority: 'medium',
      channel: 'email',
      customerId: 2,
      assigneeId: 2,
      slaBreached: false,
      createdAt: new Date('2026-07-11T09:18:00Z'),
    },
    {
      id: 117,
      subject: 'APAC workspace latency spike after deploy',
      status: 'open',
      priority: 'high',
      channel: 'phone',
      customerId: 4,
      assigneeId: 4,
      slaBreached: false,
      createdAt: new Date('2026-07-13T03:12:00Z'),
    },
    {
      id: 118,
      subject: 'Enterprise sandbox reset removed active filters',
      status: 'resolved',
      priority: 'low',
      channel: 'chat',
      customerId: 6,
      assigneeId: 1,
      slaBreached: false,
      createdAt: new Date('2026-07-05T18:44:00Z'),
    },
  ] satisfies SupportTicket[],
};
