/**
 * @fileoverview Type-performance stress fixture for `FilterState` (plan 031
 * Step 1's per-type operator discrimination).
 *
 * @remarks
 * NOT a functional test -- fed to `tsc --noEmit --extendedDiagnostics` to
 * measure the before/after cost of narrowing `FilterState`'s `operator`
 * field from the flat `FilterOperator` union to a per-type union derived
 * from `filter-operators.ts`'s `*_OPERATORS` arrays (plan 031 Step 1).
 * Shaped like the plan 011/018 perf fixture methodology: a synthetic,
 * moderately large corpus (60 columns x all 8 `FilterState` members = 480
 * explicitly-typed literal filter objects) plus narrowing functions that
 * exercise the discriminated union's control-flow analysis.
 *
 * Measure with:
 *   cd packages/core && bunx tsc --noEmit --extendedDiagnostics \
 *     tests/types/filter-perf-fixture.ts 2>&1 | grep -E "Check time|Instantiations"
 */
import type {
  BooleanFilterState,
  CustomFilterState,
  DateFilterState,
  FilterState,
  JsonFilterState,
  MultiOptionFilterState,
  NumberFilterState,
  OptionFilterState,
  TextFilterState,
} from '../../src/types/filter';
import {
  isBooleanFilterState,
  isDateFilterState,
  isNumberFilterState,
  isOptionFilterState,
  isTextFilterState,
} from '../../src/utils/type-guards';

export const textFilters: TextFilterState[] = [
  { columnId: 'text0', type: 'text', operator: 'contains', values: ['v0'] },
  { columnId: 'text1', type: 'text', operator: 'equals', values: ['v1'] },
  { columnId: 'text2', type: 'text', operator: 'startsWith', values: ['v2'] },
  { columnId: 'text3', type: 'text', operator: 'endsWith', values: ['v3'] },
  { columnId: 'text4', type: 'text', operator: 'isEmpty', values: ['v4'] },
  { columnId: 'text5', type: 'text', operator: 'isNotEmpty', values: ['v5'] },
  { columnId: 'text6', type: 'text', operator: 'contains', values: ['v6'] },
  { columnId: 'text7', type: 'text', operator: 'equals', values: ['v7'] },
  { columnId: 'text8', type: 'text', operator: 'startsWith', values: ['v8'] },
  { columnId: 'text9', type: 'text', operator: 'endsWith', values: ['v9'] },
  { columnId: 'text10', type: 'text', operator: 'isEmpty', values: ['v10'] },
  { columnId: 'text11', type: 'text', operator: 'isNotEmpty', values: ['v11'] },
  { columnId: 'text12', type: 'text', operator: 'contains', values: ['v12'] },
  { columnId: 'text13', type: 'text', operator: 'equals', values: ['v13'] },
  { columnId: 'text14', type: 'text', operator: 'startsWith', values: ['v14'] },
  { columnId: 'text15', type: 'text', operator: 'endsWith', values: ['v15'] },
  { columnId: 'text16', type: 'text', operator: 'isEmpty', values: ['v16'] },
  { columnId: 'text17', type: 'text', operator: 'isNotEmpty', values: ['v17'] },
  { columnId: 'text18', type: 'text', operator: 'contains', values: ['v18'] },
  { columnId: 'text19', type: 'text', operator: 'equals', values: ['v19'] },
  { columnId: 'text20', type: 'text', operator: 'startsWith', values: ['v20'] },
  { columnId: 'text21', type: 'text', operator: 'endsWith', values: ['v21'] },
  { columnId: 'text22', type: 'text', operator: 'isEmpty', values: ['v22'] },
  { columnId: 'text23', type: 'text', operator: 'isNotEmpty', values: ['v23'] },
  { columnId: 'text24', type: 'text', operator: 'contains', values: ['v24'] },
  { columnId: 'text25', type: 'text', operator: 'equals', values: ['v25'] },
  { columnId: 'text26', type: 'text', operator: 'startsWith', values: ['v26'] },
  { columnId: 'text27', type: 'text', operator: 'endsWith', values: ['v27'] },
  { columnId: 'text28', type: 'text', operator: 'isEmpty', values: ['v28'] },
  { columnId: 'text29', type: 'text', operator: 'isNotEmpty', values: ['v29'] },
  { columnId: 'text30', type: 'text', operator: 'contains', values: ['v30'] },
  { columnId: 'text31', type: 'text', operator: 'equals', values: ['v31'] },
  { columnId: 'text32', type: 'text', operator: 'startsWith', values: ['v32'] },
  { columnId: 'text33', type: 'text', operator: 'endsWith', values: ['v33'] },
  { columnId: 'text34', type: 'text', operator: 'isEmpty', values: ['v34'] },
  { columnId: 'text35', type: 'text', operator: 'isNotEmpty', values: ['v35'] },
  { columnId: 'text36', type: 'text', operator: 'contains', values: ['v36'] },
  { columnId: 'text37', type: 'text', operator: 'equals', values: ['v37'] },
  { columnId: 'text38', type: 'text', operator: 'startsWith', values: ['v38'] },
  { columnId: 'text39', type: 'text', operator: 'endsWith', values: ['v39'] },
  { columnId: 'text40', type: 'text', operator: 'isEmpty', values: ['v40'] },
  { columnId: 'text41', type: 'text', operator: 'isNotEmpty', values: ['v41'] },
  { columnId: 'text42', type: 'text', operator: 'contains', values: ['v42'] },
  { columnId: 'text43', type: 'text', operator: 'equals', values: ['v43'] },
  { columnId: 'text44', type: 'text', operator: 'startsWith', values: ['v44'] },
  { columnId: 'text45', type: 'text', operator: 'endsWith', values: ['v45'] },
  { columnId: 'text46', type: 'text', operator: 'isEmpty', values: ['v46'] },
  { columnId: 'text47', type: 'text', operator: 'isNotEmpty', values: ['v47'] },
  { columnId: 'text48', type: 'text', operator: 'contains', values: ['v48'] },
  { columnId: 'text49', type: 'text', operator: 'equals', values: ['v49'] },
  { columnId: 'text50', type: 'text', operator: 'startsWith', values: ['v50'] },
  { columnId: 'text51', type: 'text', operator: 'endsWith', values: ['v51'] },
  { columnId: 'text52', type: 'text', operator: 'isEmpty', values: ['v52'] },
  { columnId: 'text53', type: 'text', operator: 'isNotEmpty', values: ['v53'] },
  { columnId: 'text54', type: 'text', operator: 'contains', values: ['v54'] },
  { columnId: 'text55', type: 'text', operator: 'equals', values: ['v55'] },
  { columnId: 'text56', type: 'text', operator: 'startsWith', values: ['v56'] },
  { columnId: 'text57', type: 'text', operator: 'endsWith', values: ['v57'] },
  { columnId: 'text58', type: 'text', operator: 'isEmpty', values: ['v58'] },
  { columnId: 'text59', type: 'text', operator: 'isNotEmpty', values: ['v59'] },
];

export const numberFilters: NumberFilterState[] = [
  { columnId: 'num0', type: 'number', operator: 'equals', values: [0] },
  { columnId: 'num1', type: 'number', operator: 'notEquals', values: [1] },
  { columnId: 'num2', type: 'number', operator: 'greaterThan', values: [2] },
  { columnId: 'num3', type: 'number', operator: 'greaterThanOrEqual', values: [3] },
  { columnId: 'num4', type: 'number', operator: 'lessThan', values: [4] },
  { columnId: 'num5', type: 'number', operator: 'lessThanOrEqual', values: [5] },
  { columnId: 'num6', type: 'number', operator: 'between', values: [6] },
  { columnId: 'num7', type: 'number', operator: 'notBetween', values: [7] },
  { columnId: 'num8', type: 'number', operator: 'isNull', values: [8] },
  { columnId: 'num9', type: 'number', operator: 'isNotNull', values: [9] },
  { columnId: 'num10', type: 'number', operator: 'equals', values: [10] },
  { columnId: 'num11', type: 'number', operator: 'notEquals', values: [11] },
  { columnId: 'num12', type: 'number', operator: 'greaterThan', values: [12] },
  { columnId: 'num13', type: 'number', operator: 'greaterThanOrEqual', values: [13] },
  { columnId: 'num14', type: 'number', operator: 'lessThan', values: [14] },
  { columnId: 'num15', type: 'number', operator: 'lessThanOrEqual', values: [15] },
  { columnId: 'num16', type: 'number', operator: 'between', values: [16] },
  { columnId: 'num17', type: 'number', operator: 'notBetween', values: [17] },
  { columnId: 'num18', type: 'number', operator: 'isNull', values: [18] },
  { columnId: 'num19', type: 'number', operator: 'isNotNull', values: [19] },
  { columnId: 'num20', type: 'number', operator: 'equals', values: [20] },
  { columnId: 'num21', type: 'number', operator: 'notEquals', values: [21] },
  { columnId: 'num22', type: 'number', operator: 'greaterThan', values: [22] },
  { columnId: 'num23', type: 'number', operator: 'greaterThanOrEqual', values: [23] },
  { columnId: 'num24', type: 'number', operator: 'lessThan', values: [24] },
  { columnId: 'num25', type: 'number', operator: 'lessThanOrEqual', values: [25] },
  { columnId: 'num26', type: 'number', operator: 'between', values: [26] },
  { columnId: 'num27', type: 'number', operator: 'notBetween', values: [27] },
  { columnId: 'num28', type: 'number', operator: 'isNull', values: [28] },
  { columnId: 'num29', type: 'number', operator: 'isNotNull', values: [29] },
  { columnId: 'num30', type: 'number', operator: 'equals', values: [30] },
  { columnId: 'num31', type: 'number', operator: 'notEquals', values: [31] },
  { columnId: 'num32', type: 'number', operator: 'greaterThan', values: [32] },
  { columnId: 'num33', type: 'number', operator: 'greaterThanOrEqual', values: [33] },
  { columnId: 'num34', type: 'number', operator: 'lessThan', values: [34] },
  { columnId: 'num35', type: 'number', operator: 'lessThanOrEqual', values: [35] },
  { columnId: 'num36', type: 'number', operator: 'between', values: [36] },
  { columnId: 'num37', type: 'number', operator: 'notBetween', values: [37] },
  { columnId: 'num38', type: 'number', operator: 'isNull', values: [38] },
  { columnId: 'num39', type: 'number', operator: 'isNotNull', values: [39] },
  { columnId: 'num40', type: 'number', operator: 'equals', values: [40] },
  { columnId: 'num41', type: 'number', operator: 'notEquals', values: [41] },
  { columnId: 'num42', type: 'number', operator: 'greaterThan', values: [42] },
  { columnId: 'num43', type: 'number', operator: 'greaterThanOrEqual', values: [43] },
  { columnId: 'num44', type: 'number', operator: 'lessThan', values: [44] },
  { columnId: 'num45', type: 'number', operator: 'lessThanOrEqual', values: [45] },
  { columnId: 'num46', type: 'number', operator: 'between', values: [46] },
  { columnId: 'num47', type: 'number', operator: 'notBetween', values: [47] },
  { columnId: 'num48', type: 'number', operator: 'isNull', values: [48] },
  { columnId: 'num49', type: 'number', operator: 'isNotNull', values: [49] },
  { columnId: 'num50', type: 'number', operator: 'equals', values: [50] },
  { columnId: 'num51', type: 'number', operator: 'notEquals', values: [51] },
  { columnId: 'num52', type: 'number', operator: 'greaterThan', values: [52] },
  { columnId: 'num53', type: 'number', operator: 'greaterThanOrEqual', values: [53] },
  { columnId: 'num54', type: 'number', operator: 'lessThan', values: [54] },
  { columnId: 'num55', type: 'number', operator: 'lessThanOrEqual', values: [55] },
  { columnId: 'num56', type: 'number', operator: 'between', values: [56] },
  { columnId: 'num57', type: 'number', operator: 'notBetween', values: [57] },
  { columnId: 'num58', type: 'number', operator: 'isNull', values: [58] },
  { columnId: 'num59', type: 'number', operator: 'isNotNull', values: [59] },
];

export const dateFilters: DateFilterState[] = [
  { columnId: 'date0', type: 'date', operator: 'is', values: [new Date(2024, 0, 1)] },
  { columnId: 'date1', type: 'date', operator: 'isNot', values: [new Date(2024, 0, 2)] },
  { columnId: 'date2', type: 'date', operator: 'before', values: [new Date(2024, 0, 3)] },
  { columnId: 'date3', type: 'date', operator: 'after', values: [new Date(2024, 0, 4)] },
  { columnId: 'date4', type: 'date', operator: 'between', values: [new Date(2024, 0, 5)] },
  { columnId: 'date5', type: 'date', operator: 'notBetween', values: [new Date(2024, 0, 6)] },
  { columnId: 'date6', type: 'date', operator: 'isToday', values: [new Date(2024, 0, 7)] },
  { columnId: 'date7', type: 'date', operator: 'isYesterday', values: [new Date(2024, 0, 8)] },
  { columnId: 'date8', type: 'date', operator: 'isThisWeek', values: [new Date(2024, 0, 9)] },
  { columnId: 'date9', type: 'date', operator: 'isThisMonth', values: [new Date(2024, 0, 10)] },
  { columnId: 'date10', type: 'date', operator: 'isThisYear', values: [new Date(2024, 0, 11)] },
  { columnId: 'date11', type: 'date', operator: 'isNull', values: [new Date(2024, 0, 12)] },
  { columnId: 'date12', type: 'date', operator: 'isNotNull', values: [new Date(2024, 0, 13)] },
  { columnId: 'date13', type: 'date', operator: 'is', values: [new Date(2024, 0, 14)] },
  { columnId: 'date14', type: 'date', operator: 'isNot', values: [new Date(2024, 0, 15)] },
  { columnId: 'date15', type: 'date', operator: 'before', values: [new Date(2024, 0, 16)] },
  { columnId: 'date16', type: 'date', operator: 'after', values: [new Date(2024, 0, 17)] },
  { columnId: 'date17', type: 'date', operator: 'between', values: [new Date(2024, 0, 18)] },
  { columnId: 'date18', type: 'date', operator: 'notBetween', values: [new Date(2024, 0, 19)] },
  { columnId: 'date19', type: 'date', operator: 'isToday', values: [new Date(2024, 0, 20)] },
  { columnId: 'date20', type: 'date', operator: 'isYesterday', values: [new Date(2024, 0, 21)] },
  { columnId: 'date21', type: 'date', operator: 'isThisWeek', values: [new Date(2024, 0, 22)] },
  { columnId: 'date22', type: 'date', operator: 'isThisMonth', values: [new Date(2024, 0, 23)] },
  { columnId: 'date23', type: 'date', operator: 'isThisYear', values: [new Date(2024, 0, 24)] },
  { columnId: 'date24', type: 'date', operator: 'isNull', values: [new Date(2024, 0, 25)] },
  { columnId: 'date25', type: 'date', operator: 'isNotNull', values: [new Date(2024, 0, 26)] },
  { columnId: 'date26', type: 'date', operator: 'is', values: [new Date(2024, 0, 27)] },
  { columnId: 'date27', type: 'date', operator: 'isNot', values: [new Date(2024, 0, 1)] },
  { columnId: 'date28', type: 'date', operator: 'before', values: [new Date(2024, 0, 2)] },
  { columnId: 'date29', type: 'date', operator: 'after', values: [new Date(2024, 0, 3)] },
  { columnId: 'date30', type: 'date', operator: 'between', values: [new Date(2024, 0, 4)] },
  { columnId: 'date31', type: 'date', operator: 'notBetween', values: [new Date(2024, 0, 5)] },
  { columnId: 'date32', type: 'date', operator: 'isToday', values: [new Date(2024, 0, 6)] },
  { columnId: 'date33', type: 'date', operator: 'isYesterday', values: [new Date(2024, 0, 7)] },
  { columnId: 'date34', type: 'date', operator: 'isThisWeek', values: [new Date(2024, 0, 8)] },
  { columnId: 'date35', type: 'date', operator: 'isThisMonth', values: [new Date(2024, 0, 9)] },
  { columnId: 'date36', type: 'date', operator: 'isThisYear', values: [new Date(2024, 0, 10)] },
  { columnId: 'date37', type: 'date', operator: 'isNull', values: [new Date(2024, 0, 11)] },
  { columnId: 'date38', type: 'date', operator: 'isNotNull', values: [new Date(2024, 0, 12)] },
  { columnId: 'date39', type: 'date', operator: 'is', values: [new Date(2024, 0, 13)] },
  { columnId: 'date40', type: 'date', operator: 'isNot', values: [new Date(2024, 0, 14)] },
  { columnId: 'date41', type: 'date', operator: 'before', values: [new Date(2024, 0, 15)] },
  { columnId: 'date42', type: 'date', operator: 'after', values: [new Date(2024, 0, 16)] },
  { columnId: 'date43', type: 'date', operator: 'between', values: [new Date(2024, 0, 17)] },
  { columnId: 'date44', type: 'date', operator: 'notBetween', values: [new Date(2024, 0, 18)] },
  { columnId: 'date45', type: 'date', operator: 'isToday', values: [new Date(2024, 0, 19)] },
  { columnId: 'date46', type: 'date', operator: 'isYesterday', values: [new Date(2024, 0, 20)] },
  { columnId: 'date47', type: 'date', operator: 'isThisWeek', values: [new Date(2024, 0, 21)] },
  { columnId: 'date48', type: 'date', operator: 'isThisMonth', values: [new Date(2024, 0, 22)] },
  { columnId: 'date49', type: 'date', operator: 'isThisYear', values: [new Date(2024, 0, 23)] },
  { columnId: 'date50', type: 'date', operator: 'isNull', values: [new Date(2024, 0, 24)] },
  { columnId: 'date51', type: 'date', operator: 'isNotNull', values: [new Date(2024, 0, 25)] },
  { columnId: 'date52', type: 'date', operator: 'is', values: [new Date(2024, 0, 26)] },
  { columnId: 'date53', type: 'date', operator: 'isNot', values: [new Date(2024, 0, 27)] },
  { columnId: 'date54', type: 'date', operator: 'before', values: [new Date(2024, 0, 1)] },
  { columnId: 'date55', type: 'date', operator: 'after', values: [new Date(2024, 0, 2)] },
  { columnId: 'date56', type: 'date', operator: 'between', values: [new Date(2024, 0, 3)] },
  { columnId: 'date57', type: 'date', operator: 'notBetween', values: [new Date(2024, 0, 4)] },
  { columnId: 'date58', type: 'date', operator: 'isToday', values: [new Date(2024, 0, 5)] },
  { columnId: 'date59', type: 'date', operator: 'isYesterday', values: [new Date(2024, 0, 6)] },
];

export const booleanFilters: BooleanFilterState[] = [
  { columnId: 'bool0', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool1', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool2', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool3', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool4', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool5', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool6', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool7', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool8', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool9', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool10', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool11', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool12', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool13', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool14', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool15', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool16', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool17', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool18', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool19', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool20', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool21', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool22', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool23', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool24', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool25', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool26', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool27', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool28', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool29', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool30', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool31', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool32', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool33', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool34', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool35', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool36', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool37', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool38', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool39', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool40', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool41', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool42', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool43', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool44', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool45', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool46', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool47', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool48', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool49', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool50', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool51', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool52', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool53', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool54', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool55', type: 'boolean', operator: 'isNotNull', values: [false] },
  { columnId: 'bool56', type: 'boolean', operator: 'isTrue', values: [true] },
  { columnId: 'bool57', type: 'boolean', operator: 'isFalse', values: [false] },
  { columnId: 'bool58', type: 'boolean', operator: 'isNull', values: [true] },
  { columnId: 'bool59', type: 'boolean', operator: 'isNotNull', values: [false] },
];

export const optionFilters: OptionFilterState[] = [
  { columnId: 'opt0', type: 'option', operator: 'is', values: ['choice0'] },
  { columnId: 'opt1', type: 'option', operator: 'isNot', values: ['choice1'] },
  { columnId: 'opt2', type: 'option', operator: 'isAnyOf', values: ['choice2'] },
  { columnId: 'opt3', type: 'option', operator: 'isNoneOf', values: ['choice3'] },
  { columnId: 'opt4', type: 'option', operator: 'isNull', values: ['choice4'] },
  { columnId: 'opt5', type: 'option', operator: 'isNotNull', values: ['choice5'] },
  { columnId: 'opt6', type: 'option', operator: 'is', values: ['choice6'] },
  { columnId: 'opt7', type: 'option', operator: 'isNot', values: ['choice7'] },
  { columnId: 'opt8', type: 'option', operator: 'isAnyOf', values: ['choice8'] },
  { columnId: 'opt9', type: 'option', operator: 'isNoneOf', values: ['choice9'] },
  { columnId: 'opt10', type: 'option', operator: 'isNull', values: ['choice10'] },
  { columnId: 'opt11', type: 'option', operator: 'isNotNull', values: ['choice11'] },
  { columnId: 'opt12', type: 'option', operator: 'is', values: ['choice12'] },
  { columnId: 'opt13', type: 'option', operator: 'isNot', values: ['choice13'] },
  { columnId: 'opt14', type: 'option', operator: 'isAnyOf', values: ['choice14'] },
  { columnId: 'opt15', type: 'option', operator: 'isNoneOf', values: ['choice15'] },
  { columnId: 'opt16', type: 'option', operator: 'isNull', values: ['choice16'] },
  { columnId: 'opt17', type: 'option', operator: 'isNotNull', values: ['choice17'] },
  { columnId: 'opt18', type: 'option', operator: 'is', values: ['choice18'] },
  { columnId: 'opt19', type: 'option', operator: 'isNot', values: ['choice19'] },
  { columnId: 'opt20', type: 'option', operator: 'isAnyOf', values: ['choice20'] },
  { columnId: 'opt21', type: 'option', operator: 'isNoneOf', values: ['choice21'] },
  { columnId: 'opt22', type: 'option', operator: 'isNull', values: ['choice22'] },
  { columnId: 'opt23', type: 'option', operator: 'isNotNull', values: ['choice23'] },
  { columnId: 'opt24', type: 'option', operator: 'is', values: ['choice24'] },
  { columnId: 'opt25', type: 'option', operator: 'isNot', values: ['choice25'] },
  { columnId: 'opt26', type: 'option', operator: 'isAnyOf', values: ['choice26'] },
  { columnId: 'opt27', type: 'option', operator: 'isNoneOf', values: ['choice27'] },
  { columnId: 'opt28', type: 'option', operator: 'isNull', values: ['choice28'] },
  { columnId: 'opt29', type: 'option', operator: 'isNotNull', values: ['choice29'] },
  { columnId: 'opt30', type: 'option', operator: 'is', values: ['choice30'] },
  { columnId: 'opt31', type: 'option', operator: 'isNot', values: ['choice31'] },
  { columnId: 'opt32', type: 'option', operator: 'isAnyOf', values: ['choice32'] },
  { columnId: 'opt33', type: 'option', operator: 'isNoneOf', values: ['choice33'] },
  { columnId: 'opt34', type: 'option', operator: 'isNull', values: ['choice34'] },
  { columnId: 'opt35', type: 'option', operator: 'isNotNull', values: ['choice35'] },
  { columnId: 'opt36', type: 'option', operator: 'is', values: ['choice36'] },
  { columnId: 'opt37', type: 'option', operator: 'isNot', values: ['choice37'] },
  { columnId: 'opt38', type: 'option', operator: 'isAnyOf', values: ['choice38'] },
  { columnId: 'opt39', type: 'option', operator: 'isNoneOf', values: ['choice39'] },
  { columnId: 'opt40', type: 'option', operator: 'isNull', values: ['choice40'] },
  { columnId: 'opt41', type: 'option', operator: 'isNotNull', values: ['choice41'] },
  { columnId: 'opt42', type: 'option', operator: 'is', values: ['choice42'] },
  { columnId: 'opt43', type: 'option', operator: 'isNot', values: ['choice43'] },
  { columnId: 'opt44', type: 'option', operator: 'isAnyOf', values: ['choice44'] },
  { columnId: 'opt45', type: 'option', operator: 'isNoneOf', values: ['choice45'] },
  { columnId: 'opt46', type: 'option', operator: 'isNull', values: ['choice46'] },
  { columnId: 'opt47', type: 'option', operator: 'isNotNull', values: ['choice47'] },
  { columnId: 'opt48', type: 'option', operator: 'is', values: ['choice48'] },
  { columnId: 'opt49', type: 'option', operator: 'isNot', values: ['choice49'] },
  { columnId: 'opt50', type: 'option', operator: 'isAnyOf', values: ['choice50'] },
  { columnId: 'opt51', type: 'option', operator: 'isNoneOf', values: ['choice51'] },
  { columnId: 'opt52', type: 'option', operator: 'isNull', values: ['choice52'] },
  { columnId: 'opt53', type: 'option', operator: 'isNotNull', values: ['choice53'] },
  { columnId: 'opt54', type: 'option', operator: 'is', values: ['choice54'] },
  { columnId: 'opt55', type: 'option', operator: 'isNot', values: ['choice55'] },
  { columnId: 'opt56', type: 'option', operator: 'isAnyOf', values: ['choice56'] },
  { columnId: 'opt57', type: 'option', operator: 'isNoneOf', values: ['choice57'] },
  { columnId: 'opt58', type: 'option', operator: 'isNull', values: ['choice58'] },
  { columnId: 'opt59', type: 'option', operator: 'isNotNull', values: ['choice59'] },
];

export const multiOptionFilters: MultiOptionFilterState[] = [
  { columnId: 'multi0', type: 'multiOption', operator: 'includes', values: ['tag0'] },
  { columnId: 'multi1', type: 'multiOption', operator: 'excludes', values: ['tag1'] },
  { columnId: 'multi2', type: 'multiOption', operator: 'includesAny', values: ['tag2'] },
  { columnId: 'multi3', type: 'multiOption', operator: 'includesAll', values: ['tag3'] },
  { columnId: 'multi4', type: 'multiOption', operator: 'excludesAny', values: ['tag4'] },
  { columnId: 'multi5', type: 'multiOption', operator: 'excludesAll', values: ['tag5'] },
  { columnId: 'multi6', type: 'multiOption', operator: 'isNull', values: ['tag6'] },
  { columnId: 'multi7', type: 'multiOption', operator: 'isNotNull', values: ['tag7'] },
  { columnId: 'multi8', type: 'multiOption', operator: 'includes', values: ['tag8'] },
  { columnId: 'multi9', type: 'multiOption', operator: 'excludes', values: ['tag9'] },
  { columnId: 'multi10', type: 'multiOption', operator: 'includesAny', values: ['tag10'] },
  { columnId: 'multi11', type: 'multiOption', operator: 'includesAll', values: ['tag11'] },
  { columnId: 'multi12', type: 'multiOption', operator: 'excludesAny', values: ['tag12'] },
  { columnId: 'multi13', type: 'multiOption', operator: 'excludesAll', values: ['tag13'] },
  { columnId: 'multi14', type: 'multiOption', operator: 'isNull', values: ['tag14'] },
  { columnId: 'multi15', type: 'multiOption', operator: 'isNotNull', values: ['tag15'] },
  { columnId: 'multi16', type: 'multiOption', operator: 'includes', values: ['tag16'] },
  { columnId: 'multi17', type: 'multiOption', operator: 'excludes', values: ['tag17'] },
  { columnId: 'multi18', type: 'multiOption', operator: 'includesAny', values: ['tag18'] },
  { columnId: 'multi19', type: 'multiOption', operator: 'includesAll', values: ['tag19'] },
  { columnId: 'multi20', type: 'multiOption', operator: 'excludesAny', values: ['tag20'] },
  { columnId: 'multi21', type: 'multiOption', operator: 'excludesAll', values: ['tag21'] },
  { columnId: 'multi22', type: 'multiOption', operator: 'isNull', values: ['tag22'] },
  { columnId: 'multi23', type: 'multiOption', operator: 'isNotNull', values: ['tag23'] },
  { columnId: 'multi24', type: 'multiOption', operator: 'includes', values: ['tag24'] },
  { columnId: 'multi25', type: 'multiOption', operator: 'excludes', values: ['tag25'] },
  { columnId: 'multi26', type: 'multiOption', operator: 'includesAny', values: ['tag26'] },
  { columnId: 'multi27', type: 'multiOption', operator: 'includesAll', values: ['tag27'] },
  { columnId: 'multi28', type: 'multiOption', operator: 'excludesAny', values: ['tag28'] },
  { columnId: 'multi29', type: 'multiOption', operator: 'excludesAll', values: ['tag29'] },
  { columnId: 'multi30', type: 'multiOption', operator: 'isNull', values: ['tag30'] },
  { columnId: 'multi31', type: 'multiOption', operator: 'isNotNull', values: ['tag31'] },
  { columnId: 'multi32', type: 'multiOption', operator: 'includes', values: ['tag32'] },
  { columnId: 'multi33', type: 'multiOption', operator: 'excludes', values: ['tag33'] },
  { columnId: 'multi34', type: 'multiOption', operator: 'includesAny', values: ['tag34'] },
  { columnId: 'multi35', type: 'multiOption', operator: 'includesAll', values: ['tag35'] },
  { columnId: 'multi36', type: 'multiOption', operator: 'excludesAny', values: ['tag36'] },
  { columnId: 'multi37', type: 'multiOption', operator: 'excludesAll', values: ['tag37'] },
  { columnId: 'multi38', type: 'multiOption', operator: 'isNull', values: ['tag38'] },
  { columnId: 'multi39', type: 'multiOption', operator: 'isNotNull', values: ['tag39'] },
  { columnId: 'multi40', type: 'multiOption', operator: 'includes', values: ['tag40'] },
  { columnId: 'multi41', type: 'multiOption', operator: 'excludes', values: ['tag41'] },
  { columnId: 'multi42', type: 'multiOption', operator: 'includesAny', values: ['tag42'] },
  { columnId: 'multi43', type: 'multiOption', operator: 'includesAll', values: ['tag43'] },
  { columnId: 'multi44', type: 'multiOption', operator: 'excludesAny', values: ['tag44'] },
  { columnId: 'multi45', type: 'multiOption', operator: 'excludesAll', values: ['tag45'] },
  { columnId: 'multi46', type: 'multiOption', operator: 'isNull', values: ['tag46'] },
  { columnId: 'multi47', type: 'multiOption', operator: 'isNotNull', values: ['tag47'] },
  { columnId: 'multi48', type: 'multiOption', operator: 'includes', values: ['tag48'] },
  { columnId: 'multi49', type: 'multiOption', operator: 'excludes', values: ['tag49'] },
  { columnId: 'multi50', type: 'multiOption', operator: 'includesAny', values: ['tag50'] },
  { columnId: 'multi51', type: 'multiOption', operator: 'includesAll', values: ['tag51'] },
  { columnId: 'multi52', type: 'multiOption', operator: 'excludesAny', values: ['tag52'] },
  { columnId: 'multi53', type: 'multiOption', operator: 'excludesAll', values: ['tag53'] },
  { columnId: 'multi54', type: 'multiOption', operator: 'isNull', values: ['tag54'] },
  { columnId: 'multi55', type: 'multiOption', operator: 'isNotNull', values: ['tag55'] },
  { columnId: 'multi56', type: 'multiOption', operator: 'includes', values: ['tag56'] },
  { columnId: 'multi57', type: 'multiOption', operator: 'excludes', values: ['tag57'] },
  { columnId: 'multi58', type: 'multiOption', operator: 'includesAny', values: ['tag58'] },
  { columnId: 'multi59', type: 'multiOption', operator: 'includesAll', values: ['tag59'] },
];

export const jsonFilters: JsonFilterState[] = [
  { columnId: 'json0', type: 'json', operator: 'contains', values: [{ k: 0 }] },
  { columnId: 'json1', type: 'json', operator: 'equals', values: [{ k: 1 }] },
  { columnId: 'json2', type: 'json', operator: 'isEmpty', values: [{ k: 2 }] },
  { columnId: 'json3', type: 'json', operator: 'isNotEmpty', values: [{ k: 3 }] },
  { columnId: 'json4', type: 'json', operator: 'isNull', values: [{ k: 4 }] },
  { columnId: 'json5', type: 'json', operator: 'isNotNull', values: [{ k: 5 }] },
  { columnId: 'json6', type: 'json', operator: 'contains', values: [{ k: 6 }] },
  { columnId: 'json7', type: 'json', operator: 'equals', values: [{ k: 7 }] },
  { columnId: 'json8', type: 'json', operator: 'isEmpty', values: [{ k: 8 }] },
  { columnId: 'json9', type: 'json', operator: 'isNotEmpty', values: [{ k: 9 }] },
  { columnId: 'json10', type: 'json', operator: 'isNull', values: [{ k: 10 }] },
  { columnId: 'json11', type: 'json', operator: 'isNotNull', values: [{ k: 11 }] },
  { columnId: 'json12', type: 'json', operator: 'contains', values: [{ k: 12 }] },
  { columnId: 'json13', type: 'json', operator: 'equals', values: [{ k: 13 }] },
  { columnId: 'json14', type: 'json', operator: 'isEmpty', values: [{ k: 14 }] },
  { columnId: 'json15', type: 'json', operator: 'isNotEmpty', values: [{ k: 15 }] },
  { columnId: 'json16', type: 'json', operator: 'isNull', values: [{ k: 16 }] },
  { columnId: 'json17', type: 'json', operator: 'isNotNull', values: [{ k: 17 }] },
  { columnId: 'json18', type: 'json', operator: 'contains', values: [{ k: 18 }] },
  { columnId: 'json19', type: 'json', operator: 'equals', values: [{ k: 19 }] },
  { columnId: 'json20', type: 'json', operator: 'isEmpty', values: [{ k: 20 }] },
  { columnId: 'json21', type: 'json', operator: 'isNotEmpty', values: [{ k: 21 }] },
  { columnId: 'json22', type: 'json', operator: 'isNull', values: [{ k: 22 }] },
  { columnId: 'json23', type: 'json', operator: 'isNotNull', values: [{ k: 23 }] },
  { columnId: 'json24', type: 'json', operator: 'contains', values: [{ k: 24 }] },
  { columnId: 'json25', type: 'json', operator: 'equals', values: [{ k: 25 }] },
  { columnId: 'json26', type: 'json', operator: 'isEmpty', values: [{ k: 26 }] },
  { columnId: 'json27', type: 'json', operator: 'isNotEmpty', values: [{ k: 27 }] },
  { columnId: 'json28', type: 'json', operator: 'isNull', values: [{ k: 28 }] },
  { columnId: 'json29', type: 'json', operator: 'isNotNull', values: [{ k: 29 }] },
  { columnId: 'json30', type: 'json', operator: 'contains', values: [{ k: 30 }] },
  { columnId: 'json31', type: 'json', operator: 'equals', values: [{ k: 31 }] },
  { columnId: 'json32', type: 'json', operator: 'isEmpty', values: [{ k: 32 }] },
  { columnId: 'json33', type: 'json', operator: 'isNotEmpty', values: [{ k: 33 }] },
  { columnId: 'json34', type: 'json', operator: 'isNull', values: [{ k: 34 }] },
  { columnId: 'json35', type: 'json', operator: 'isNotNull', values: [{ k: 35 }] },
  { columnId: 'json36', type: 'json', operator: 'contains', values: [{ k: 36 }] },
  { columnId: 'json37', type: 'json', operator: 'equals', values: [{ k: 37 }] },
  { columnId: 'json38', type: 'json', operator: 'isEmpty', values: [{ k: 38 }] },
  { columnId: 'json39', type: 'json', operator: 'isNotEmpty', values: [{ k: 39 }] },
  { columnId: 'json40', type: 'json', operator: 'isNull', values: [{ k: 40 }] },
  { columnId: 'json41', type: 'json', operator: 'isNotNull', values: [{ k: 41 }] },
  { columnId: 'json42', type: 'json', operator: 'contains', values: [{ k: 42 }] },
  { columnId: 'json43', type: 'json', operator: 'equals', values: [{ k: 43 }] },
  { columnId: 'json44', type: 'json', operator: 'isEmpty', values: [{ k: 44 }] },
  { columnId: 'json45', type: 'json', operator: 'isNotEmpty', values: [{ k: 45 }] },
  { columnId: 'json46', type: 'json', operator: 'isNull', values: [{ k: 46 }] },
  { columnId: 'json47', type: 'json', operator: 'isNotNull', values: [{ k: 47 }] },
  { columnId: 'json48', type: 'json', operator: 'contains', values: [{ k: 48 }] },
  { columnId: 'json49', type: 'json', operator: 'equals', values: [{ k: 49 }] },
  { columnId: 'json50', type: 'json', operator: 'isEmpty', values: [{ k: 50 }] },
  { columnId: 'json51', type: 'json', operator: 'isNotEmpty', values: [{ k: 51 }] },
  { columnId: 'json52', type: 'json', operator: 'isNull', values: [{ k: 52 }] },
  { columnId: 'json53', type: 'json', operator: 'isNotNull', values: [{ k: 53 }] },
  { columnId: 'json54', type: 'json', operator: 'contains', values: [{ k: 54 }] },
  { columnId: 'json55', type: 'json', operator: 'equals', values: [{ k: 55 }] },
  { columnId: 'json56', type: 'json', operator: 'isEmpty', values: [{ k: 56 }] },
  { columnId: 'json57', type: 'json', operator: 'isNotEmpty', values: [{ k: 57 }] },
  { columnId: 'json58', type: 'json', operator: 'isNull', values: [{ k: 58 }] },
  { columnId: 'json59', type: 'json', operator: 'isNotNull', values: [{ k: 59 }] },
];

export const customFilters: CustomFilterState[] = [
  { columnId: 'custom0', type: 'custom', operator: 'equals', values: [0] },
  { columnId: 'custom1', type: 'custom', operator: 'notEquals', values: [1] },
  { columnId: 'custom2', type: 'custom', operator: 'isNull', values: [2] },
  { columnId: 'custom3', type: 'custom', operator: 'isNotNull', values: [3] },
  { columnId: 'custom4', type: 'custom', operator: 'equals', values: [4] },
  { columnId: 'custom5', type: 'custom', operator: 'notEquals', values: [5] },
  { columnId: 'custom6', type: 'custom', operator: 'isNull', values: [6] },
  { columnId: 'custom7', type: 'custom', operator: 'isNotNull', values: [7] },
  { columnId: 'custom8', type: 'custom', operator: 'equals', values: [8] },
  { columnId: 'custom9', type: 'custom', operator: 'notEquals', values: [9] },
  { columnId: 'custom10', type: 'custom', operator: 'isNull', values: [10] },
  { columnId: 'custom11', type: 'custom', operator: 'isNotNull', values: [11] },
  { columnId: 'custom12', type: 'custom', operator: 'equals', values: [12] },
  { columnId: 'custom13', type: 'custom', operator: 'notEquals', values: [13] },
  { columnId: 'custom14', type: 'custom', operator: 'isNull', values: [14] },
  { columnId: 'custom15', type: 'custom', operator: 'isNotNull', values: [15] },
  { columnId: 'custom16', type: 'custom', operator: 'equals', values: [16] },
  { columnId: 'custom17', type: 'custom', operator: 'notEquals', values: [17] },
  { columnId: 'custom18', type: 'custom', operator: 'isNull', values: [18] },
  { columnId: 'custom19', type: 'custom', operator: 'isNotNull', values: [19] },
  { columnId: 'custom20', type: 'custom', operator: 'equals', values: [20] },
  { columnId: 'custom21', type: 'custom', operator: 'notEquals', values: [21] },
  { columnId: 'custom22', type: 'custom', operator: 'isNull', values: [22] },
  { columnId: 'custom23', type: 'custom', operator: 'isNotNull', values: [23] },
  { columnId: 'custom24', type: 'custom', operator: 'equals', values: [24] },
  { columnId: 'custom25', type: 'custom', operator: 'notEquals', values: [25] },
  { columnId: 'custom26', type: 'custom', operator: 'isNull', values: [26] },
  { columnId: 'custom27', type: 'custom', operator: 'isNotNull', values: [27] },
  { columnId: 'custom28', type: 'custom', operator: 'equals', values: [28] },
  { columnId: 'custom29', type: 'custom', operator: 'notEquals', values: [29] },
  { columnId: 'custom30', type: 'custom', operator: 'isNull', values: [30] },
  { columnId: 'custom31', type: 'custom', operator: 'isNotNull', values: [31] },
  { columnId: 'custom32', type: 'custom', operator: 'equals', values: [32] },
  { columnId: 'custom33', type: 'custom', operator: 'notEquals', values: [33] },
  { columnId: 'custom34', type: 'custom', operator: 'isNull', values: [34] },
  { columnId: 'custom35', type: 'custom', operator: 'isNotNull', values: [35] },
  { columnId: 'custom36', type: 'custom', operator: 'equals', values: [36] },
  { columnId: 'custom37', type: 'custom', operator: 'notEquals', values: [37] },
  { columnId: 'custom38', type: 'custom', operator: 'isNull', values: [38] },
  { columnId: 'custom39', type: 'custom', operator: 'isNotNull', values: [39] },
  { columnId: 'custom40', type: 'custom', operator: 'equals', values: [40] },
  { columnId: 'custom41', type: 'custom', operator: 'notEquals', values: [41] },
  { columnId: 'custom42', type: 'custom', operator: 'isNull', values: [42] },
  { columnId: 'custom43', type: 'custom', operator: 'isNotNull', values: [43] },
  { columnId: 'custom44', type: 'custom', operator: 'equals', values: [44] },
  { columnId: 'custom45', type: 'custom', operator: 'notEquals', values: [45] },
  { columnId: 'custom46', type: 'custom', operator: 'isNull', values: [46] },
  { columnId: 'custom47', type: 'custom', operator: 'isNotNull', values: [47] },
  { columnId: 'custom48', type: 'custom', operator: 'equals', values: [48] },
  { columnId: 'custom49', type: 'custom', operator: 'notEquals', values: [49] },
  { columnId: 'custom50', type: 'custom', operator: 'isNull', values: [50] },
  { columnId: 'custom51', type: 'custom', operator: 'isNotNull', values: [51] },
  { columnId: 'custom52', type: 'custom', operator: 'equals', values: [52] },
  { columnId: 'custom53', type: 'custom', operator: 'notEquals', values: [53] },
  { columnId: 'custom54', type: 'custom', operator: 'isNull', values: [54] },
  { columnId: 'custom55', type: 'custom', operator: 'isNotNull', values: [55] },
  { columnId: 'custom56', type: 'custom', operator: 'equals', values: [56] },
  { columnId: 'custom57', type: 'custom', operator: 'notEquals', values: [57] },
  { columnId: 'custom58', type: 'custom', operator: 'isNull', values: [58] },
  { columnId: 'custom59', type: 'custom', operator: 'isNotNull', values: [59] },
];

export const allFilters: FilterState[] = [
  ...textFilters,
  ...numberFilters,
  ...dateFilters,
  ...booleanFilters,
  ...optionFilters,
  ...multiOptionFilters,
  ...jsonFilters,
  ...customFilters,
];

/**
 * Narrowing / control-flow stress: force the checker to resolve each
 * member's narrowed `operator`/`values` shape through the type-guard
 * functions, mirroring real consumer code (managers, adapters, UI).
 */
export function describeFilter(filter: FilterState): string {
  if (isTextFilterState(filter)) {
    return `text:${filter.operator}:${filter.values.join(',')}`;
  }
  if (isNumberFilterState(filter)) {
    return `number:${filter.operator}:${filter.values.join(',')}`;
  }
  if (isDateFilterState(filter)) {
    return `date:${filter.operator}:${filter.values.length}`;
  }
  if (isBooleanFilterState(filter)) {
    return `boolean:${filter.operator}:${filter.values.join(',')}`;
  }
  if (isOptionFilterState(filter)) {
    return `option:${filter.operator}:${filter.values.join(',')}`;
  }
  switch (filter.type) {
    case 'multiOption':
      return `multiOption:${filter.operator}`;
    case 'json':
      return `json:${filter.operator}`;
    case 'custom':
      return `custom:${filter.operator}`;
    default:
      return 'unknown';
  }
}

export const descriptions: string[] = allFilters.map(describeFilter);
